app = "fitp-monitor-webkit"
primary_region = "ams"

[processes]
  app = ".venv/bin/uvicorn server:app --host 0.0.0.0 --port 8000"
  worker = ".venv/bin/python main.py"

[http_service]
  internal_port = 8000
  processes = ["app"]

[[vm]]
  processes = ["app"]
  memory = "256mb"
  cpus = 1

[[vm]]
  processes = ["worker"]
  memory = "512mb"
  cpus = 1

[services.worker]
  processes = ["worker"]
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1