app = "fitp-monitor-webkit"
primary_region = "ams"

[build]

[processes]
  app = ".venv/bin/uvicorn server:app --host 0.0.0.0 --port 8000"
  worker = ".venv/bin/python main.py"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# VM per il web server
[[vm]]
  processes = ["app"]
  memory = "256mb"
  cpus = 1

# VM per il worker OCR
[[vm]]
  processes = ["worker"]
  memory = "512mb"
  cpus = 1
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1